import streamlit as st
import pandas as pd
import plotly.graph_objects as go
from datetime import datetime
from fpdf import FPDF
import time

from logic.scanner import scan_wifi

st.set_page_config(page_title="TwinGuard AI", page_icon="🛡️", layout="wide")

# SESSION STATE
if 'logs' not in st.session_state: st.session_state.logs = []
if 'df' not in st.session_state: st.session_state.df = pd.DataFrame()
if 'blocked_list' not in st.session_state: st.session_state.blocked_list = [] 

st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700&display=swap');
* {font-family: 'Poppins', sans-serif!important; text-transform: none!important;}
.main{ background:#0f172a; }
.title{ font-size:38px; color:#00E5FF; font-weight:bold; }
.metric-card{ background:#1e293b; padding:20px; border-radius:15px; text-align:center; }
.metric-number{ color:#00E5FF; font-size:35px; font-weight:bold; }
.blocked{ background:#7f1d1d!important; border:2px solid red; }
div.stButton > button{ background:#00E5FF; color:#0f172a; font-weight:600; border-radius:10px; }
</style>
""",unsafe_allow_html=True)

page = st.sidebar.radio("Navigation", ["Dashboard","Threat History","Blocked List","Settings"])
st.sidebar.title("TwinGuard AI")
st.sidebar.success("System Online")

st.markdown("""
<div class="title">
🛡 TwinGuard-AI
</div>

<h4 style='color:#CBD5E1; margin-top:-10px;'>
Evil Twin Wi-Fi Detection & Prevention System
</h4>
""", unsafe_allow_html=True)
# ==========================
# Dashboard Information Bar
# ==========================

today = datetime.now()

c1, c2, c3 = st.columns(3)

with c1:
    st.info(f"📅 Date: {today.strftime('%d %B %Y')}")

with c2:
    st.info(f"🕒 Time: {today.strftime('%I:%M:%S %p')}")

with c3:
    st.success("🟢 Backend Status: Online")




# ==========================
# PDF GENERATOR
# ==========================
def create_pdf(logs_df):

    pdf = FPDF()
    pdf.add_page()

    # ---------- Title ----------
    pdf.set_font("Arial", "B", 18)
    pdf.cell(0, 12, "TwinGuard-AI", ln=True, align="C")

    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, "Wi-Fi Threat Detection Report", ln=True, align="C")

    pdf.ln(5)

    # ---------- Report Information ----------
    pdf.set_font("Arial", "", 11)

    pdf.cell(
        0,
        8,
        f"Generated On: {datetime.now().strftime('%d-%b-%Y %I:%M:%S %p')}",
        ln=True,
    )

    pdf.cell(
        0,
        8,
        f"Total Detection Records: {len(logs_df)}",
        ln=True,
    )

    pdf.ln(5)

    # ---------- Table Header ----------
    pdf.set_font("Arial", "B", 10)

    pdf.cell(25, 8, "Time", 1)
    pdf.cell(45, 8, "SSID", 1)
    pdf.cell(50, 8, "BSSID", 1)
    pdf.cell(35, 8, "Status", 1)
    pdf.cell(25, 8, "Risk", 1)

    pdf.ln()

    # ---------- Table ----------
    pdf.set_font("Arial", "", 9)

    for _, row in logs_df.iterrows():

        pdf.cell(25, 8, str(row["time"]), 1)
        pdf.cell(45, 8, str(row["ssid"])[:20], 1)
        pdf.cell(50, 8, str(row["bssid"]), 1)
        pdf.cell(35, 8, str(row["status"])[:15], 1)
        pdf.cell(25, 8, str(row["risk"]), 1)

        pdf.ln()

    # ---------- Footer ----------
    pdf.ln(8)

    pdf.set_font("Arial", "I", 9)

    pdf.multi_cell(
        0,
        6,
        "This report was automatically generated by TwinGuard-AI. "
        "It summarizes the wireless networks detected during the scan, "
        "their security status, and associated risk level.",
    )

    return bytes(pdf.output(dest="S"))
# ==========================
# PAGE 1: DASHBOARD
# ==========================
if page == "Dashboard":

    scan = st.button(
        "🔄 Scan Wi-Fi Networks",
        use_container_width=True,
        type="primary"
    )

    if scan:

        with st.spinner("🔍 Scanning nearby Wi-Fi networks..."):

            progress = st.progress(0)

            for i in range(100):
                time.sleep(0.015)
                progress.progress(i + 1)

            progress.empty()

            scan_data = scan_wifi()

            st.session_state.df = pd.DataFrame(scan_data["results"])
            st.session_state.logs = scan_data["logs"]
            st.session_state.blocked_list = scan_data["blocked"]
            st.session_state.summary = scan_data["summary"]

        st.success("✅ Scan Completed Successfully!")

    df = st.session_state.df
    

    if not df.empty:

        summary = st.session_state.summary

        total_networks = summary["total_networks"]
        safe_networks = summary["safe_networks"]
        dangerous = summary["threats_found"]
        risk_score = summary["security_score"]
        
        c1, c2, c3, c4 = st.columns(4)

        with c1:
            st.metric("📶 Networks Found", total_networks)

        with c2:
            st.metric("✅ Safe Networks", safe_networks)

        with c3:
            st.metric("🚨 Threats Found", dangerous)

        with c4:
            st.metric("🛡 Security Score", f"{risk_score}%")

        st.markdown("## 📶 Available Wi-Fi Networks")
        st.caption("Select a network below to perform a detailed security analysis.")
        for index, row in df.iterrows():
            with st.container():

                col1, col2, col3, col4, col5, col6 = st.columns([2, 3, 2, 2, 3, 1])
                with col1:
                    st.write(f"**{row['ssid']}**")

                with col2:
                    st.write(row["bssid"])

                with col3:
                    st.write(f"{row['signal']} dBm")

                with col4:
                    st.write(row["security"])

                with col5:
                    st.write("")

                with col6:
                    if st.button("Check", key=f"check{index}"):

                        st.session_state.selected = row.to_dict()

                        st.rerun()
        if "selected" in st.session_state:

           row = st.session_state.selected

           st.divider()

           st.markdown("## 🔍 Analysis Report")

           left, right = st.columns(2)

           with left:

               st.markdown("### 📡 Network Details")

               st.write(f"**SSID:** {row['ssid']}")
               st.write(f"**BSSID:** {row['bssid']}")
               st.write(f"**Category:** {row['category']}")

           with right:

               st.markdown("### 🛡 Security Assessment")

               st.metric("Status", row["status"])
               st.metric("Risk Level", row["risk"])
               st.progress(row["confidence"] / 100)
               st.caption(f"Confidence Score: {row['confidence']}%")

           if row["status"] == "Verified":

               st.success("✅ This Wi-Fi network is verified and safe to connect.")

           else:

               st.error("🚨 Potential Evil Twin detected. Avoid connecting to this network.")

           st.warning(f"### ⚠ Detection Reason\n{row['reason']}")

           st.info(f"### 💡 Recommendation\n{row['recommendation']}")

           if row["status"] == "Potential Evil Twin":

              if st.button("⛔ Block This Network"):

                 st.session_state.blocked_list.append(row)

                 st.success("Network added to Blocked List.")

                 st.rerun()
    
# ==========================
# PAGE 2: THREAT HISTORY
# ==========================
elif page == "Threat History":

    st.markdown("## 📜 Threat History")

    if len(st.session_state.logs) > 0:

        logs_df = pd.DataFrame(st.session_state.logs)

        st.metric("Detection Records", len(logs_df))

        st.dataframe(
            logs_df,
            use_container_width=True,
            hide_index=True
        )

        pdf_bytes = create_pdf(logs_df)

        st.download_button(
            "⬇ Download PDF Report",
            pdf_bytes,
            file_name="TwinGuard_Report.pdf",
            mime="application/pdf"
        )

    else:

        st.info("No scan history available.")


# ==========================
# PAGE 3: BLOCKED LIST
# ==========================
elif page == "Blocked List":

    st.markdown("## ⛔ Blocked Networks")

    if len(st.session_state.blocked_list) > 0:

        for index, network in enumerate(st.session_state.blocked_list):

            with st.container():

                st.error(f"🚨 {network['ssid']}")

                st.write(f"**BSSID:** {network['bssid']}")
                st.write(f"**Risk:** {network['risk']}")

                if "status" in network:
                    st.write(f"**Status:** {network['status']}")

                if "confidence" in network:
                    st.write(f"**Confidence:** {network['confidence']}%")

                if "reason" in network:
                    st.warning(f"**Reason:** {network['reason']}")

                col1, col2 = st.columns([5, 1])

                with col2:

                    if st.button("🔓 Unblock", key=f"unblock_{index}"):

                        st.session_state.blocked_list.remove(network)

                        st.success("Network Unblocked Successfully!")

                        st.rerun()

                st.divider()

    

# ==========================
# PAGE 4: SETTINGS
# ==========================
elif page == "Settings":

    st.markdown("## ⚙️ System Settings")

    col1, col2 = st.columns(2)

    with col1:

        st.success("🟢 Detection Engine : Active")
        st.success("🟢 Scanner Module : Connected")
        st.success("🟢 Backend Status : Online")

    with col2:

        st.info("📂 Network Database : Loaded")
        st.info("🛡 Version : TwinGuard-AI v1.0")
        st.info("👩‍💻 Mode : Simulation Prototype")

    st.divider()

    st.subheader("📌 System Information")

    st.write("**Project:** TwinGuard-AI")
    st.write("**Purpose:** Evil Twin Wi-Fi Detection & Prevention")
    st.write("**Platform:** Python + Streamlit")
    st.write("**Course:** Security Architecture")
    st.write("**University:** Hamdard University")
    st.write("**Year:** 2026")

    st.divider()

    st.subheader("👩‍💻 Development Team")

    st.markdown("""
- **Nabiha Arshad**
- **Rabia**
- **Kanza**
""")

    st.divider()

    if st.button("🗑 Clear Detection History"):

        st.session_state.logs = []

        st.success("Detection history cleared successfully.")


# ==========================
# FOOTER
# ==========================

st.markdown("---")

st.caption(
    "🛡 TwinGuard-AI v1.0 | Developed by Group Zeta (Nabiha Arshad • Rabia Shah • Kanza Sohail) | "
    "Security Architecture Project | Hamdard University | © 2026"
)